# Python 3.10 경량 이미지를 기반으로 사용
FROM python:3.10-slim

# 작업 디렉토리를 /app으로 설정
WORKDIR /app

# 컴파일러 및 필수 라이브러리 설치
RUN apt-get update && \
    apt-get install -y gcc librdkafka-dev build-essential --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

# Python 경로를 설정하여 src 디렉토리를 인식하도록 함
ENV PYTHONPATH=/app

# 서비스 계정 파일을 컨테이너로 복사
COPY ./secrets/google/credentials.json /app/secrets/google/credentials.json

# GOOGLE_APPLICATION_CREDENTIALS 환경 변수 설정
ENV GOOGLE_APPLICATION_CREDENTIALS="/app/secrets/google/credentials.json"

# 의존성 설치 - requirements.txt 복사 및 설치
COPY ./requirements-api.txt .
RUN pip install --no-cache-dir -r requirements-api.txt

# 소스 코드 복사
COPY ./src /app/src

# FastAPI 포트 노출
EXPOSE 8080

# 환경 변수 설정
ENV GCS_BUCKET_NAME="teckwahkr-gcs"

# FastAPI Webhook 실행 (uvicorn 사용)
CMD ["uvicorn", "src.api.main_api:app", "--host", "0.0.0.0", "--port", "8080"]
