version: '3.8'
services:
  pyspark:
    build: ..
    container_name: pyspark_master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
      - MODE=local  # 로컬 모드 설정
    ports:
      - "7077:7077"
      - "4040:4040"
    volumes:
      - ../src:/app/src
      - ../models:/app/models
      - ../output:/app/output
#  teckwah-models-service:
#    build:
#      context: ..
#      dockerfile: docker/Dockerfile
#    image: teckwah-models:latest
#    container_name: teckwah-models-service
#    environment:
#      - GOOGLE_APPLICATION_CREDENTIALS="/app/secrets/google/credentials.json"#    ports:
#      - "8080:8080"
#    volumes:
#      - ../src:/app/src
#      - ../secrets:/app/secrets
#    command: [ "uvicorn", "src.api.main_api:app", "--host", "0.0.0.0", "--port", "8080" ]
#
#  dash_views-service:
#    build:
#      context: ..
#      dockerfile: docker/Dockerfile
#    image: teckwah-dash_views:latest
#    container_name: dash_service
#    environment:
#      - GOOGLE_APPLICATION_CREDENTIALS="/app/secrets/google/credentials.json"
#      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
#    ports:
#      - "8050:8050"
#    volumes:
#      - ../src:/app/src
#      - ../secrets:/app/secrets
#    command: [ "python", "src/dash_app/dashboard_app.py" ]
