version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  pyspark_app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SHEET_ID: "1x4P2VO-ZArT7ibSYywFIBXUTapBhUnE4_ouVMKrKBwc"
      RANGE_NAME: "Sheet1!A1:O1000"
      SERVICE_ACCOUNT_FILE: "/app/oauth/google/credentials.json"
    volumes:
      - ../oauth/google/credentials.json:/app/oauth/google/credentials.json
    depends_on:
      - kafka
    command: python3 /app/src/main.py
