services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    container_name: zookeeper_service
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:6.2.1
    container_name: kafka_broker
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  pyspark:
    image: bitnami/spark:3.3.0
    container_name: pyspark_master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
    ports:
      - "7077:7077"
      - "4040:4040"
    volumes:
      - ./src:/app

  airflow:
    image: puckel/docker-airflow:1.10.9
    container_name: airflow_scheduler
    environment:
      - LOAD_EX=n
      - EXECUTOR=LocalExecutor
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/usr/local/airflow/dags

  teckwah-data-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: teckwah-data:latest
    container_name: teckwah-data-service
    volumes:
      - ./src:/app/src
      - ./oauth:/app/oauth
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS="/app/oauth/google/credentials.json"
    depends_on:
      - kafka
