# docker/Dockerfile

FROM python:3.10-slim

# 프로토콜 버퍼 컴파일러 설치
RUN apt-get update && apt-get install -y protobuf-compiler

# 작업 디렉토리 설정
WORKDIR /app

# 필요한 파일 복사
COPY ./src /app/src
COPY ./proto /app/proto
COPY ./config /app/config

# 필요한 패키지 설치
RUN pip install --no-cache-dir -r config/requirements.txt

# 프로토콜 버퍼 컴파일
RUN protoc -I=./proto --python_out=./proto ./proto/delivery_status.proto

# 실행할 스크립트 지정
CMD ["python", "src/main.py"]
