# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: delivery_status.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'delivery_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64\x65livery_status.proto\"\xa4\x02\n\x0e\x44\x65liveryStatus\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x12\n\norder_date\x18\x02 \x01(\t\x12\x0f\n\x07ship_to\x18\x03 \x01(\t\x12\x0b\n\x03\x65ta\x18\x04 \x01(\t\x12\x0b\n\x03sla\x18\x05 \x01(\t\x12\x0f\n\x07\x63\x61rrier\x18\x06 \x01(\t\x12\x17\n\x0ftracking_number\x18\x07 \x01(\t\x12\x0e\n\x06status\x18\x08 \x01(\t\x12\x0b\n\x03\x64ps\x18\t \x01(\t\x12\x11\n\tship_date\x18\n \x01(\t\x12\x15\n\rdelivery_date\x18\x0b \x01(\t\x12\x11\n\trecipient\x18\x0c \x01(\t\x12\x1a\n\x12\x63ustomer_reference\x18\r \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x0e \x01(\t\x12\x10\n\x08\x63omments\x18\x0f \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'delivery_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DELIVERYSTATUS']._serialized_start=26
  _globals['_DELIVERYSTATUS']._serialized_end=318
# @@protoc_insertion_point(module_scope)
